version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-covoiturage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: voiture1
      MYSQL_DATABASE: covoiturage
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  app:
    build: .
    container_name: covoiturage-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: